# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .random import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_infoblox.record as __record
    record = __record
else:
    record = _utilities.lazy_import('pulumi_infoblox.record')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "infoblox",
  "mod": "index",
  "fqn": "pulumi_infoblox",
  "classes": {
   "infoblox:index:Random": "Random"
  }
 },
 {
  "pkg": "infoblox",
  "mod": "record",
  "fqn": "pulumi_infoblox.record",
  "classes": {
   "infoblox:record:a": "A"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "infoblox",
  "token": "pulumi:providers:infoblox",
  "fqn": "pulumi_infoblox",
  "class": "Provider"
 }
]
"""
)
